<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Testscript execution is started]]>
    </line>
  </reporter-output>
  <suite started-at="2024-01-27T10:20:04 IST" name="Default suite" finished-at="2024-01-27T10:20:27 IST" duration-ms="22770">
    <groups>
    </groups>
    <test started-at="2024-01-27T10:20:04 IST" name="Default test" finished-at="2024-01-27T10:20:27 IST" duration-ms="22770">
      <class name="Module.CreateLeadTest">
        <test-method is-config="true" signature="BS()[pri:0, instance:Module.CreateLeadTest@408d971b]" started-at="2024-01-27T10:20:04 IST" name="BS" finished-at="2024-01-27T10:20:04 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BS -->
        <test-method is-config="true" signature="BC()[pri:0, instance:Module.CreateLeadTest@408d971b]" started-at="2024-01-27T10:20:04 IST" name="BC" finished-at="2024-01-27T10:20:10 IST" duration-ms="5548" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BC -->
        <test-method is-config="true" signature="BM()[pri:0, instance:Module.CreateLeadTest@408d971b]" started-at="2024-01-27T10:20:10 IST" name="BM" finished-at="2024-01-27T10:20:14 IST" duration-ms="4543" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BM -->
        <test-method signature="CreateLead()[pri:0, instance:Module.CreateLeadTest@408d971b]" started-at="2024-01-27T10:20:14 IST" name="CreateLead" finished-at="2024-01-27T10:20:23 IST" duration-ms="8931" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Deccan] but found [Pune]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Deccan] but found [Pune]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Module.CreateLeadTest.CreateLead(CreateLeadTest.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Testscript execution is started]]>
            </line>
          </reporter-output>
        </test-method> <!-- CreateLead -->
        <test-method is-config="true" signature="AM()[pri:0, instance:Module.CreateLeadTest@408d971b]" started-at="2024-01-27T10:20:23 IST" name="AM" finished-at="2024-01-27T10:20:26 IST" duration-ms="3306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AM -->
        <test-method is-config="true" signature="AC()[pri:0, instance:Module.CreateLeadTest@408d971b]" started-at="2024-01-27T10:20:27 IST" name="AC" finished-at="2024-01-27T10:20:27 IST" duration-ms="132" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AC -->
        <test-method is-config="true" signature="AS()[pri:0, instance:Module.CreateLeadTest@408d971b]" started-at="2024-01-27T10:20:27 IST" name="AS" finished-at="2024-01-27T10:20:27 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AS -->
      </class> <!-- Module.CreateLeadTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
